/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author mark
 */
public final class inicio extends javax.swing.JFrame {
    
    cliente cliente;
    habitaciones1 habitaciones1;
    reservacion reservacion;
    JF_Detalles_reservacion jf_Detalles_reservacion;
    Usuarios Usuarios;

    

    /**
     * Creates new form inicio
     * @throws java.sql.SQLException
     */
    public inicio() throws SQLException {
        this.cliente = new cliente(this);
        this.habitaciones1 = new habitaciones1(this);
        this.reservacion = new reservacion (this);
        this.jf_Detalles_reservacion = new JF_Detalles_reservacion(this);
        this.Usuarios = new Usuarios(this);
        initComponents();
        transpareciaButton();
    }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void transpareciaButton(){
    
        jb_habitaciones.setOpaque(false);
        jb_habitaciones.setContentAreaFilled(false);
        jb_habitaciones.setBorderPainted(false);
        jb_clientes.setOpaque(false);
        jb_clientes.setContentAreaFilled(false);
        jb_clientes.setBorderPainted(false);
        jb_reservaciones.setOpaque(false);
        jb_reservaciones.setContentAreaFilled(false);
        jb_reservaciones.setBorderPainted(false);
        jb_salir.setOpaque(false);
        jb_salir.setContentAreaFilled(false);
        jb_salir.setBorderPainted(false);
        jb_detalles.setOpaque(false);
        jb_detalles.setContentAreaFilled(false);
        jb_detalles.setBorderPainted(false);
        jb_usuarios.setOpaque(false);
        jb_usuarios.setContentAreaFilled(false);
        jb_usuarios.setBorderPainted(false);
        
}
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_habitaciones = new javax.swing.JButton();
        jb_reservaciones = new javax.swing.JButton();
        jb_clientes = new javax.swing.JButton();
        jl_habitaciones = new javax.swing.JLabel();
        jb_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jl_reservacion = new javax.swing.JLabel();
        jb_detalles = new javax.swing.JButton();
        jl_Detalles_reservacion = new javax.swing.JLabel();
        jb_usuarios = new javax.swing.JButton();
        jl_usuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_habitaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Documents\\bootstrap-3.3.7-dist\\Sample Pictures\\HLA.jpg")); // NOI18N
        jb_habitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_habitacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jb_habitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 180, 150));

        jb_reservaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Documents\\bootstrap-3.3.7-dist\\2723379160_9f9cda250e_n.jpg")); // NOI18N
        jb_reservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reservacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jb_reservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, 150));

        jb_clientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\mark\\Documents\\bootstrap-3.3.7-dist\\9082593296_7b352dace4_n.jpg")); // NOI18N
        jb_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(jb_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 20, 170, 150));

        jl_habitaciones.setForeground(new java.awt.Color(255, 255, 255));
        jl_habitaciones.setText("         Habitaciones");
        getContentPane().add(jl_habitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 180, 140, 20));

        jb_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/th.jpg"))); // NOI18N
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 120, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("         Clientes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 180, 110, -1));

        jl_reservacion.setForeground(new java.awt.Color(255, 255, 255));
        jl_reservacion.setText("   Reservaciones");
        getContentPane().add(jl_reservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, -1));

        jb_detalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/descarga_1.jpg"))); // NOI18N
        jb_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_detallesActionPerformed(evt);
            }
        });
        getContentPane().add(jb_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 170));

        jl_Detalles_reservacion.setForeground(new java.awt.Color(255, 255, 255));
        jl_Detalles_reservacion.setText("Detalles_reservacion");
        getContentPane().add(jl_Detalles_reservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jb_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        jb_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/descarga (2).jpg"))); // NOI18N
        jb_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_usuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jb_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 190, 170));

        jl_usuarios.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuarios.setText("        Usuarios");
        getContentPane().add(jl_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/aaf5294a47a7c4e617953d98fe8c0b82.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_reservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reservacionesActionPerformed
        // TODO add your handling code here:
         reservacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_reservacionesActionPerformed

    private void jb_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clientesActionPerformed
        // TODO add your handling code here:
         cliente.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jb_clientesActionPerformed

    private void jb_habitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_habitacionesActionPerformed
        // TODO add your handling code here:
        habitaciones1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jb_habitacionesActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
        // TODO add your handling code here:
       dispose();
       this.setVisible(false);
    }//GEN-LAST:event_jb_salirActionPerformed

    private void jb_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_detallesActionPerformed
        jf_Detalles_reservacion.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jb_detallesActionPerformed

    private void jb_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_usuariosActionPerformed
         Usuarios.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jb_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new inicio().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_clientes;
    private javax.swing.JButton jb_detalles;
    private javax.swing.JButton jb_habitaciones;
    private javax.swing.JButton jb_reservaciones;
    private javax.swing.JButton jb_salir;
    private javax.swing.JButton jb_usuarios;
    private javax.swing.JLabel jl_Detalles_reservacion;
    private javax.swing.JLabel jl_habitaciones;
    private javax.swing.JLabel jl_reservacion;
    private javax.swing.JLabel jl_usuarios;
    // End of variables declaration//GEN-END:variables
}
