/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;
import javax.swing.JOptionPane;

import java.sql.Connection; 
import java.sql.ResultSet; 
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author mark
 */
public final class Usuario_cuenta extends javax.swing.JFrame {

    
    
  

    /**
     * Creates new form Usuario_cuenta
     */
    public Usuario_cuenta() {
        this.cn = mysql.Connectar();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jl_fondo_usuario = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        jl_password = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jb_Entrar = new javax.swing.JButton();
        jpf_password = new javax.swing.JPasswordField();
        jb_salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_fondo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/imagesYZVLSX93.jpg"))); // NOI18N
        getContentPane().add(jl_fondo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, 184));

        jl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuario.setText("Usuario");
        getContentPane().add(jl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jl_password.setForeground(new java.awt.Color(255, 255, 255));
        jl_password.setText("Contraseña");
        getContentPane().add(jl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));
        getContentPane().add(jtf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 97, -1));

        jb_Entrar.setText("Entrar");
        jb_Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EntrarMouseClicked(evt);
            }
        });
        getContentPane().add(jb_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));
        getContentPane().add(jpf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 97, -1));

        jb_salir.setText("Salir");
        jb_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salirActionPerformed(evt);
            }
        });
        getContentPane().add(jb_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       Hotel Los Angeles ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("            Iniciar Sesion ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 40, 250, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/imagesF9ZA9ZUE.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/imagenes/aaf5294a47a7c4e617953d98fe8c0b82.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 420, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EntrarMouseClicked
         String usu,pass;
     String DatoCapturado = "";
     usu = jtf_usuario.getText();
     pass = new String(jpf_password.getPassword());
     
     String sql= "select * from usuarios where usuario ='"+usu+"' AND password='"+pass+"'";
     
     try{
         Statement sta = cn.createStatement();
         ResultSet rst=sta.executeQuery(sql);
         
         while (rst.next())
         {
             DatoCapturado = rst.getString("usuario");
         }
         
            
            if (DatoCapturado.equals(""))
            {
             JOptionPane.showMessageDialog(null,"usuario no valido","contraseña o usuario es incorrecta",JOptionPane.OK_OPTION);
            }
            
            
            else
            {
            JOptionPane.showMessageDialog(this,"usuario valido");
            inicio entrar =new inicio();
            entrar.setVisible(true);
            this.setVisible(false);
            }
         
     
     } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,"usuario valido"+ex);
      }
    }//GEN-LAST:event_jb_EntrarMouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jb_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salirActionPerformed
          System.exit(0);
    }//GEN-LAST:event_jb_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jb_Entrar;
    private javax.swing.JButton jb_salir;
    private javax.swing.JLabel jl_fondo_usuario;
    private javax.swing.JLabel jl_password;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JPasswordField jpf_password;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
Conectar mysql= new Conectar();
Connection cn;


}
